# Generated by Django 2.0.7 on 2020-08-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200818_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor_plate',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
