# Generated by Django 2.0.7 on 2020-08-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200818_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor_part',
            name='part_element2',
        ),
        migrations.AlterField(
            model_name='motor_part',
            name='part_element1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.motor_element'),
        ),
        migrations.AlterField(
            model_name='motor_type',
            name='type_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.motor_part'),
        ),
    ]
