# Generated by Django 2.0.7 on 2020-08-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_fix_history_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor_part',
            name='part_element',
            field=models.ManyToManyField(blank=True, null=True, to='home.motor_element'),
        ),
    ]
