# Generated by Django 2.0.7 on 2020-08-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200825_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=30)),
                ('element_expired_mile', models.CharField(blank=True, max_length=30, null=True)),
                ('element_expired_year', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='motor_plate',
            name='new_elements',
            field=models.ManyToManyField(blank=True, null=True, to='home.new_elements'),
        ),
    ]
