# Generated by Django 2.0.7 on 2020-08-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200825_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_elements',
            name='element_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
