# Generated by Django 2.0.7 on 2020-08-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_new_elements_element_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix_history',
            name='element_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
