# Generated by Django 2.0.7 on 2020-08-25 14:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200825_2323'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='motor_plate',
            managers=[
                ('get_all_elements', django.db.models.manager.Manager()),
            ],
        ),
    ]
