# Generated by Django 2.0.7 on 2020-08-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200826_0030'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='motor_plate',
            managers=[
            ],
        ),
    ]
