# Generated by Django 2.0.7 on 2020-08-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='motor_element',
        ),
        migrations.DeleteModel(
            name='motor_part',
        ),
    ]
