# Generated by Django 2.0.7 on 2020-08-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200816_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='motor_element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=30)),
                ('element_name', models.CharField(max_length=30)),
                ('element_expired_mile', models.CharField(blank=True, max_length=30, null=True)),
                ('element_expired_year', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='motor_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_title', models.CharField(max_length=30)),
                ('part_element1', models.CharField(max_length=30)),
                ('part_element2', models.CharField(max_length=30)),
            ],
        ),
    ]
