# Generated by Django 2.0.7 on 2020-08-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_motor_element_motor_part'),
    ]

    operations = [
        migrations.DeleteModel(
            name='motor_element',
        ),
        migrations.DeleteModel(
            name='motor_part',
        ),
    ]
